# Generated by Django 5.1.2 on 2025-01-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_farmerproduct',
        ),
    ]
