# Generated by Django 5.1.2 on 2025-01-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_rename_district_id_tbl_price_district_and_more'),
        ('Farmer', '0004_delete_tbl_farmerproduct'),
        ('Guest', '0018_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerproduct_stock', models.CharField(max_length=50)),
                ('farmerproduct_date', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
            ],
        ),
    ]
