# Generated by Django 5.1.2 on 2025-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productrule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.TextField()),
                ('consequents', models.TextField()),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
            ],
        ),
    ]
