# Generated by Django 5.1.2 on 2025-01-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0006_tbl_productrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_productrule',
            name='antecedents',
            field=models.JSONField(),
        ),
    ]
