# Generated by Django 5.1.2 on 2025-01-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0007_alter_tbl_productrule_antecedents'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('complaint_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.CharField(max_length=50)),
                ('request_sending', models.CharField(max_length=50)),
                ('request_receiving', models.CharField(max_length=50)),
            ],
        ),
    ]
