# Generated by Django 5.1.2 on 2025-01-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0008_tbl_complaint_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
