# Generated by Django 5.1.2 on 2025-01-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0009_delete_tbl_complaint'),
        ('Guest', '0018_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_file', models.FileField(upload_to='Assets/Crop/Photo/')),
                ('crop_content', models.CharField(max_length=50)),
                ('crop_output', models.CharField(max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer')),
            ],
        ),
    ]
