# Generated by Django 5.1.5 on 2025-02-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0010_tbl_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
