# Generated by Django 5.1.5 on 2025-02-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0014_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
