# Generated by Django 5.1.5 on 2025-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0016_tbl_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
    ]
