# Generated by Django 5.1.5 on 2025-02-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0017_alter_tbl_request_request_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
