# Generated by Django 5.1.5 on 2025-02-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_district_id_tbl_price_district_and_more'),
        ('Farmer', '0018_delete_tbl_request'),
        ('Guest', '0018_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('send_qty', models.CharField(max_length=50)),
                ('receive_qty', models.CharField(max_length=50)),
                ('receive_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_farmer', to='Guest.tbl_farmer')),
                ('receive_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_product', to='Admin.tbl_product')),
                ('send_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_farmer', to='Guest.tbl_farmer')),
                ('send_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_product', to='Admin.tbl_product')),
            ],
        ),
    ]
