# Generated by Django 5.1.6 on 2025-02-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0021_delete_tbl_complaint'),
        ('Guest', '0021_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='farmer_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_payment', to='Guest.tbl_farmer'),
        ),
    ]
