# Generated by Django 5.1.6 on 2025-02-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_district_id_tbl_price_district_and_more'),
        ('Farmer', '0022_tbl_request_farmer_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_frequent_swaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('keyword', models.CharField(default='Frequent', max_length=20)),
                ('antecedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedent_product', to='Admin.tbl_product')),
                ('consequent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequent_product', to='Admin.tbl_product')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_productrule',
        ),
    ]
