# Generated by Django 5.1.6 on 2025-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0023_tbl_frequent_swaps_delete_tbl_productrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_farmerproduct',
            name='farmerproduct_price',
            field=models.IntegerField(default=0),
        ),
    ]
