# Generated by Django 5.1.2 on 2024-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('farmer_email', models.CharField(max_length=50)),
                ('farmer_address', models.CharField(max_length=100)),
                ('farmer_contact', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
