# Generated by Django 5.1.2 on 2024-12-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_farmer',
        ),
    ]
