# Generated by Django 5.1.2 on 2024-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_tbl_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=100)),
            ],
        ),
    ]
