# Generated by Django 5.1.2 on 2024-12-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
