# Generated by Django 5.1.2 on 2024-12-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='product_price',
        ),
    ]
