# Generated by Django 5.1.2 on 2024-12-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_price',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='tbl_price',
            old_name='product_id',
            new_name='product',
        ),
    ]
