# Generated by Django 5.1.5 on 2025-02-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
