# Generated by Django 5.1.2 on 2024-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='customer_cont',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
