# Generated by Django 5.1.2 on 2024-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_customer_customer_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='customer_cont',
            field=models.CharField(max_length=10),
        ),
    ]
