# Generated by Django 5.1.2 on 2024-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_customer_customer_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('farmer_email', models.CharField(max_length=50)),
                ('farmer_contact', models.CharField(max_length=50)),
                ('farmer_address', models.CharField(max_length=50)),
                ('farmer_password', models.CharField(max_length=50)),
            ],
        ),
    ]
