# Generated by Django 5.1.2 on 2024-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_farmer',
            name='farmer_status',
            field=models.IntegerField(default=0),
        ),
    ]
