# Generated by Django 5.1.2 on 2024-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_farmer_farmer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='customer_status',
            field=models.IntegerField(default=0),
        ),
    ]
