# Generated by Django 5.1.2 on 2024-12-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_customer_customer_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customer',
        ),
        migrations.DeleteModel(
            name='tbl_farmer',
        ),
    ]
