# Generated by Django 5.1.2 on 2024-12-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customer',
        ),
        migrations.DeleteModel(
            name='tbl_farmer',
        ),
    ]
