# Generated by Django 5.1.2 on 2024-12-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_farmer',
        ),
    ]
