# Generated by Django 5.1.2 on 2024-12-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
        ('Guest', '0011_delete_tbl_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('farmer_email', models.CharField(max_length=50)),
                ('farmer_contact', models.CharField(max_length=50)),
                ('farmer_address', models.CharField(max_length=50)),
                ('farmer_photo', models.FileField(upload_to='Assets/Farmer/Photo/')),
                ('farmer_proof', models.FileField(upload_to='Assets/Farmer/Proof/')),
                ('farmer_password', models.CharField(max_length=50)),
                ('farmer_status', models.IntegerField(default=0)),
                ('farmer_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
