# Generated by Django 5.1.2 on 2024-12-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customer',
        ),
    ]
