# Generated by Django 5.1.2 on 2024-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_delete_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_cont', models.CharField(max_length=10)),
                ('customer_photo', models.FileField(upload_to='Assets/Customer/Photo')),
                ('customer_pass', models.CharField(max_length=10)),
                ('customer_status', models.IntegerField(default=0)),
            ],
        ),
    ]
