# Generated by Django 5.1.2 on 2024-12-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customer',
        ),
    ]
