# Generated by Django 5.1.2 on 2024-12-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
        ('Guest', '0017_delete_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_cont', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=50)),
                ('customer_photo', models.FileField(upload_to='Assets/Customer/Photo')),
                ('customer_pass', models.CharField(max_length=10)),
                ('customer_status', models.IntegerField(default=0)),
                ('customer_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
