# Generated by Django 5.1.5 on 2025-02-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
