# Generated by Django 5.1.6 on 2025-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0021_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(default='Not Yet Replayed', max_length=50),
        ),
    ]
